### ISSUE TITLE
Tensorflow benchmark does not work

### ISSUE THREAD

**Issue by xumukns** [hclhkbu/dlbench#12]
Could you help me please to start tesnsorflow benchmark?
The python script calls a bash script "t.sh" from home folder. What is it? As I commented it out, I've got:

> File "fcn5_mnist.py", line 2, in <module>
>     import models1 as models
> ImportError: No module named models1
> finished with execute time: .942914696
> ./t.sh: Zeile 10: deactivate: Command not found.

What do I wrong?

Thanks a lot in advance

**Comment by shyhuai** [comment]
"t.sh" is the script to run the benchmark, and it receives the arguments of batch_size, epochs and deviceId. There is a typos in the file of fcn5_minst.py. I have fixed it. Please pull the newest code and try again. You can run with the command like: 
```batch_size=1024 epochs=40 deviceId=0 ./t.sh```

**Comment by xumukns** [comment]
Thank you for the fast response and help. It seems to work.
Could you say please, the lines in the t.sh

> ...
> source ~/tf11/bin/activate
> ...
> deactivate
> ...

Can I comment it out? I get always in the log file "./t.sh: line 10: deactivate: command not found..."

And other question. if I use the option "-post True" I get:

> Traceback (most recent call last):
>   File "post_record.py", line 3, in <module>
>     import settings
> ImportError: No module named settings

where can find this part "settings"? Is it critical ?

Thanks

best regards
Sergey

**Comment by shyhuai** [comment]
The ```deactivate``` command is used for virtual python environment of TensorFlow, so if you don't use the virtual environment, you can comment it out.
Please use the option of "-post False" for experiments. It's a neglectable option.

**Comment by xumukns** [comment]
Thank you very much. It works.
