### ISSUE TITLE
Where to download the `data1000.txt`?

### ISSUE THREAD

**Issue by b1ueshad0w** [hclhkbu/dlbench#28]
From line 17 in `dlbench/synthetic/experiments/tensorflow/fc/ffn.py`:
```
...
data = np.loadtxt('/home/comp/csshshi/data/cntk/data1000.txt')
...
``` 
I wonder which dataset `data1000.txt` belongs to?

**Comment by shyhuai** [comment]
`ffn.py` is obsolete, please use `ffn26752l6.py` instead in the same folder.

**Comment by b1ueshad0w** [comment]
Thanks.
