### ISSUE TITLE
mxnet with mkldnn enabled

### ISSUE THREAD

**Issue by mli** [hclhkbu/dlbench#5]
Thanks for the great effects to make the benchmark.

I'm curious that if mxnet is enabled mkldnn or not for the CPU performance. 

To enable it, we need to clone the the recent code and then enable

```
USE_MKL2017 = 1
USE_MKL2017_EXPERIMENTAL = 1
```

in config.mk.

@zhenlinluo @glingyan

**Comment by shyhuai** [comment]
Thank you for your suggestion. The current tested version of MXNet is not the latest, so the mkldnn is not enabled. We will enable the provided configurations when we test the newest version of framework.

**Comment by pineking** [comment]
@shyhuai could you test the newest version of mxnet especially for RNN/LSTM example? since a new PR ( https://github.com/dmlc/mxnet/pull/4618 ) is merged into the master branch just now.
see the issue: https://github.com/dmlc/mxnet/issues/4878

**Comment by shyhuai** [comment]
Sure, we will put it into our next-round benchmark with all the newest versions of frameworks.

**Comment by FreemanX** [comment]
MXNET scripts updated. MKL and mxnet.rnn are now being used in new scripts which have been tested with mxnet0.9.5
