### ISSUE TITLE
Tiny-dnn

### ISSUE THREAD

**Issue by bhack** [hclhkbu/dlbench#8]
Are you interested in tiny-dnn with multiple engines?

**Comment by shyhuai** [comment]
It seems that tiny-dnn is outstanding on CPU platform, but it doesn't support GPU. Currently, we are mainly focusing on the frameworks that support GPU.

**Comment by bhack** [comment]
Yes it is on working. I will ping this issue when we will have also a full functional gpu code path.

**Comment by shyhuai** [comment]
That's great. Could you help to provide the scripts like current existing tools to running different networks (i.e., FCN-R, AlexNet-R, ResNet-56 and LSTM) after you are ready for GPU platform so that we can evaluate the performance in our hardware platform in time.
